name: Create CRX Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: |
          pnpm install
          pnpm install -g crx

      - name: Build project
        run: pnpm build

      - name: Make Scripts executable
        run: chmod +x scripts/*.sh
        working-directory: ./.github/

      - name: Create CRX package
        run: ./.github/scripts/create-crx.sh
        env:
          CHROME_CRX_SIGNING_KEY: ${{ secrets.CHROME_CRX_SIGNING_KEY }}

      # Generate a tag if we're not already on a tag push
      - name: Generate tag if needed
        if: startsWith(github.ref, 'refs/tags/') != true
        id: tag
        run: |
          # Get current date in YYYY.MM.DD format
          DATE=$(date +'%Y.%m.%d')
          # Create a tag with date and short commit hash
          TAG="v${DATE}-$(git rev-parse --short HEAD)"
          echo "Generated tag: $TAG"
          echo "new_tag=$TAG" >> $GITHUB_OUTPUT
          # Create and push the tag
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a $TAG -m "Automated release $TAG"
          git push origin $TAG

      # 6. Create a GitHub Release and upload the .crx file as an asset
      - name: Create GitHub Release for existing tag
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: 'build/infynium-focus.crx'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create release for the tag we just created
      - name: Create GitHub Release for new tag
        if: startsWith(github.ref, 'refs/tags/') != true
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          files: 'build/infynium-focus.crx'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
